name: Build image

on:
  workflow_call:

jobs:
  release:
    runs-on: ubuntu-latest
    if: github.event_name == 'release'
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v2
       with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}} 
     - name: Publish release docker image
       uses: docker/build-push-action@v3
       with:
         context: .
         push: true
         tags: |
           ghcr.io/netified/license-manager-api:latest
           ghcr.io/netified/license-manager-api:${{ github.event.release.tag_name }}
     - name: Image digest
       run: echo ${{ steps.docker_build.outputs.digest }}
  develop:
    runs-on: ubuntu-latest
    if: github.event_name != 'release'
    steps:
     - name: Checkout
       uses: actions/checkout@v3
     - name: Login to GitHub Container Registry
       uses: docker/login-action@v2
       with:
        registry: ghcr.io
        username: ${{github.actor}}
        password: ${{secrets.GITHUB_TOKEN}} 
     - name: Publish develop docker image
       uses: docker/build-push-action@v3
       with:
         context: .
         push: true
         tags: |
           ghcr.io/netified/license-manager-api:develop