name: Update Server

on:
  workflow_call:
    inputs:
      imageVersion:
        description: 'Image version'     
        required: true
        type: string
      environment:
        description: 'Environment'     
        required: true
        type: string
  workflow_dispatch:
    inputs:
      imageVersion:
        description: 'Image version'     
        required: true
        default: 'latest' 
        type: string
      environment:
        description: 'Environment'     
        required: true
        default: 'dev' 
        type: choice
        options:
         - dev
         - prd
jobs:
  build:
    runs-on: [self-hosted]
    steps:
    - name: Checkout
      uses: actions/checkout@v3

    - name: Login to GitHub Container Registry
      uses: docker/login-action@v2
      with:
       registry: ghcr.io
       username: ${{github.actor}}
       password: ${{secrets.GITHUB_TOKEN}} 

    - name: Setup environment variables
      run: | 
        touch .env
        echo API_VERSION='${{ inputs.imageVersion }}' >> .env
        
    - name: Update associated images
      run: "sudo /usr/local/bin/docker-compose -f docker-compose.${{ inputs.environment }}.yml -p netified_lm_${{ inputs.environment }}_api pull"

    - name: Stop Containers
      run: "sudo /usr/local/bin/docker-compose -f docker-compose.${{ inputs.environment }}.yml -p netified_lm_${{ inputs.environment }}_api stop"

    - name: Start Containers
      run: "sudo /usr/local/bin/docker-compose -f docker-compose.${{ inputs.environment }}.yml -p netified_lm_${{ inputs.environment }}_api up -d --build"